name: "Terraform Plan"
description: "Run steps for Terraform Plan"

inputs:
  path:
    description: "Path to Terraform's code directory"
    required: true

runs:
  using: composite
  steps:
  - name: Terraform Plan
    shell: bash
    id: tf_plan
    run: |
      terraform plan -var-file=backend/terraform.dev.tfvars --out=${{ env.TF_PLAN_OUTPUT_FILE_NAME }}
    working-directory: ${{ inputs.path }}
    continue-on-error: true

  - name: Terraform Plan Status
    shell: bash
    if: steps.tf_plan.outcome == 'failure'
    run: exit 1
      
  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    with:
      name: "${{ env.TF_PLAN_OUTPUT_FILE_NAME }}"
      path: "${{ inputs.path }}/${{ env.TF_PLAN_OUTPUT_FILE_NAME }}"
      retention-days: 7