name: "Infrastructure Provisioning"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dev_plan:
    name: Terraform plan DEV
    uses: "./.github/workflows/prepare-tf-to-execution.yaml"
    with:
      terraform_command: "plan"
    secrets: inherit

  dev_apply:
    name: "Terraform apply in DEV env"
    uses: "./.github/workflows/prepare-tf-to-execution.yaml"
    with:
      terraform_command: "apply --auto-approve"
    secrets: inherit
    needs: [ dev_plan ]
